//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Boat
{
    [Serializable]
    public class CommandMsg : Message
    {
        public const string k_RosMessageName = "boat_msgs/Command";
        public override string RosMessageName => k_RosMessageName;

        public float vel;
        public float yaw;
        public float winch;

        public CommandMsg()
        {
            this.vel = 0.0f;
            this.yaw = 0.0f;
            this.winch = 0.0f;
        }

        public CommandMsg(float vel, float yaw, float winch)
        {
            this.vel = vel;
            this.yaw = yaw;
            this.winch = winch;
        }

        public static CommandMsg Deserialize(MessageDeserializer deserializer) => new CommandMsg(deserializer);

        private CommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.vel);
            deserializer.Read(out this.yaw);
            deserializer.Read(out this.winch);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.vel);
            serializer.Write(this.yaw);
            serializer.Write(this.winch);
        }

        public override string ToString()
        {
            return "CommandMsg: " +
            "\nvel: " + vel.ToString() +
            "\nyaw: " + yaw.ToString() +
            "\nwinch: " + winch.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
