//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Boat
{
    [Serializable]
    public class EnvInitRequest : Message
    {
        public const string k_RosMessageName = "boat_msgs/EnvInit";
        public override string RosMessageName => k_RosMessageName;

        public EnvParamsMsg requested;

        public EnvInitRequest()
        {
            this.requested = new EnvParamsMsg();
        }

        public EnvInitRequest(EnvParamsMsg requested)
        {
            this.requested = requested;
        }

        public static EnvInitRequest Deserialize(MessageDeserializer deserializer) => new EnvInitRequest(deserializer);

        private EnvInitRequest(MessageDeserializer deserializer)
        {
            this.requested = EnvParamsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.requested);
        }

        public override string ToString()
        {
            return "EnvInitRequest: " +
            "\nrequested: " + requested.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
