//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Boat
{
    [Serializable]
    public class EnvInitResponse : Message
    {
        public const string k_RosMessageName = "boat_msgs/EnvInit";
        public override string RosMessageName => k_RosMessageName;

        public EnvParamsMsg implemented;

        public EnvInitResponse()
        {
            this.implemented = new EnvParamsMsg();
        }

        public EnvInitResponse(EnvParamsMsg implemented)
        {
            this.implemented = implemented;
        }

        public static EnvInitResponse Deserialize(MessageDeserializer deserializer) => new EnvInitResponse(deserializer);

        private EnvInitResponse(MessageDeserializer deserializer)
        {
            this.implemented = EnvParamsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.implemented);
        }

        public override string ToString()
        {
            return "EnvInitResponse: " +
            "\nimplemented: " + implemented.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
