//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Boat
{
    [Serializable]
    public class ResetResponse : Message
    {
        public const string k_RosMessageName = "boat_msgs/Reset";
        public override string RosMessageName => k_RosMessageName;

        public string response;

        public ResetResponse()
        {
            this.response = "";
        }

        public ResetResponse(string response)
        {
            this.response = response;
        }

        public static ResetResponse Deserialize(MessageDeserializer deserializer) => new ResetResponse(deserializer);

        private ResetResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.response);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.response);
        }

        public override string ToString()
        {
            return "ResetResponse: " +
            "\nresponse: " + response.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
