//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Boat
{
    [Serializable]
    public class ResetRequest : Message
    {
        public const string k_RosMessageName = "boat_msgs/Reset";
        public override string RosMessageName => k_RosMessageName;


        public ResetRequest()
        {
        }
        public static ResetRequest Deserialize(MessageDeserializer deserializer) => new ResetRequest(deserializer);

        private ResetRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "ResetRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
