//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Boat
{
    [Serializable]
    public class SaveRequest : Message
    {
        public const string k_RosMessageName = "boat_msgs/Save";
        public override string RosMessageName => k_RosMessageName;

        public string folder;

        public SaveRequest()
        {
            this.folder = "";
        }

        public SaveRequest(string folder)
        {
            this.folder = folder;
        }

        public static SaveRequest Deserialize(MessageDeserializer deserializer) => new SaveRequest(deserializer);

        private SaveRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.folder);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.folder);
        }

        public override string ToString()
        {
            return "SaveRequest: " +
            "\nfolder: " + folder.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
